// Generated by CoffeeScript 1.6.3
define(function() {
  var customBindings;
  customBindings = function() {
    ko.bindingHandlers.sideMenuOpen = {
      init: function(element, valueAccessor) {
        var el;
        el = $(element);
        if (el.hammer == null) {
          return;
        }
        el.hammer().on("swiperight dragright", function(event) {
          var options;
          event.gesture.preventDefault();
          event.gesture.stopPropagation();
          event.gesture.stopDetect();
          options = valueAccessor();
          $('a.open-menu').click();
        });
      }
    };
    ko.bindingHandlers.sideMenuClose = {
      init: function(element, valueAccessor) {
        var el;
        el = $(element);
        if (el.hammer == null) {
          return;
        }
        el.hammer().on("swipeleft dragleft", function(event) {
          var options;
          event.gesture.preventDefault();
          event.gesture.stopPropagation();
          event.gesture.stopDetect();
          options = valueAccessor();
          $('a.open-close').click();
        });
      }
    };
    return ko.bindingHandlers.tap = {
      init: function(element, valueAccessor) {
        var tapBinding, tapHelper;
        tapHelper = $("#tapHelper");
        if (!($("#tapHelper").length > 0)) {
          $("body").append("<div id='tapHelper' style='display: none; position: absolute; width: 3px; height: 3px; z-index: 5000;'></div>");
          tapHelper = $("#tapHelper");
          tapHelper.on("click", function(event) {
            event.preventDefault();
            tapHelper.hide();
          });
        }
        return tapBinding = new TapBinding(element, valueAccessor, tapHelper);
      }
    };
  };
  return customBindings;
});
